apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  labels:
      app.kubernetes.io/name: {{.Values.name}}
      app.kubernetes.io/part-of: {{.Values.name}}
      app: {{.Values.name}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8088"
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: {{.Values.nameServicePort1}}
    port: {{.Values.servicePort1}}
    targetPort: {{.Values.serviceTargetPort1}}
    nodePort: 30888
    protocol: TCP
  - name: {{.Values.nameServicePort2}}
    port: {{.Values.servicePort2}}
    targetPort: {{.Values.serviceTargetPort2}}
    protocol: TCP
  selector:
    app: {{.Values.name}}