apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  labels:
      app.kubernetes.io/name: {{.Values.name}}
      app.kubernetes.io/part-of: {{.Values.name}}
      app: {{.Values.name}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8088"
spec:
  type: {{.Values.serviceType}}
  ports:
{{- if .Values.prodNameServicePort}}
  - name: {{.Values.prodNameServicePort}}
    port: {{.Values.prodServicePort}}
    targetPort: {{.Values.prodServiceTargetPort}}
    nodePort: 30888
    protocol: TCP
{{- end}}
{{- if .Values.devNameServicePort}}
  - name: {{.Values.devNameServicePort}}
    port: {{.Values.devServicePort}}
    targetPort: {{.Values.devServiceTargetPort}}
    nodePort: 33888
    protocol: TCP
{{- end}}
  - name: {{.Values.namePromPort}}
    port: {{.Values.promServicePort}}
    targetPort: {{.Values.promeTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}